app: cms-service
harbor_project: cms
DNET_PRODUCT: cms
image: harbor.qianfan123.com/{{harbor_project}}/{{app}}
setup_image: harbor.qianfan123.com/{{harbor_project}}/cms-rdb-setup
setup_db: cms
_type: backend
enable_hpa: true
enable_rdb: true
resources:
  default:
    limits_cpu: 1000m
    limits_memory: 1060Mi
    requests_cpu: 10m
    requests_memory: 960Mi
  production:
    limits_cpu: 900m
    limits_memory: 3096Mi
    requests_cpu: 300m
    requests_memory: 3096Mi
sensitive_keys:

- '{{mongodb_password|mandatory}}'
- '{{datasource_password|mandatory}}'
- '{{redisPassword|mandatory}}'
